Q.7 = (b) Securing communication
Q.8 = (b) AES
Q.9 =  (c) RSA
Q.10 = (a) Symmetric uses one key; asymmetric uses two keys
Q.11 = (c) Blowfish
Q.12 = (d) Weak key attack
Q.13 = (c) Resistance to Shor’s algorithm
Q.14 = (b) Using nonces and timestamps
Q.15 =  (a) PGP
Q.16 = (a) An encryption method that is immune to quantum computing attacks